### PR TITLE
Use Cobalt to start Brave

### PR DESCRIPTION
**Pull request by refi64**
Cobalt is basically a tool I created to avoid having to individually PR changes everywhere when one of the many copy-pasted wrapper scripts needs changes :sweat_smile: It centralizes everything and pretty much takes out the need for most wrapper scripts, as in this case.

(The "mimic" warning dialog is also redone and looks significantly prettier.)

### CODE REVIEW

**Comment by refi64** [comment]
Re-tested to confirm it works locally.

**Comment by rany2** [comment]
I can't seem to be able to launch it.  Any tips?

```
$ flatpak run com.brave.Browser 
Failed to get expose-pids state: Failed to read 'version'
```

**Comment by rany2** [comment]
It seems to work inconsistently, i tried again while changing nothing and it worked fine...  Not sure how I could help with understanding the bug.

**Comment by rany2** [comment]
I figured out the cause, while I was debugging something triggered flatpak-portal to start. The bug appears when flatpak-portal is not started; however, cobalt's debugging doesn't inform me the issue is flatpak-portal: 

With flatpak-portal not started:
```
user@debian:~$ systemctl --user status flatpak-portal.service 
● flatpak-portal.service - flatpak portal
     Loaded: loaded (/usr/lib/systemd/user/flatpak-portal.service; static)
     Active: inactive (dead)

Jul 25 00:46:41 debian systemd[1052]: Starting flatpak portal...
Jul 25 00:46:41 debian systemd[1052]: Started flatpak portal.
Jul 25 00:59:30 debian systemd[1052]: flatpak-portal.service: Succeeded.
Jul 25 12:42:36 debian systemd[1052]: Starting flatpak portal...
Jul 25 12:42:36 debian systemd[1052]: Started flatpak portal.
Jul 25 12:53:02 debian systemd[1052]: Stopping flatpak portal...
Jul 25 12:53:02 debian systemd[1052]: flatpak-portal.service: Succeeded.
Jul 25 12:53:02 debian systemd[1052]: Stopped flatpak portal.
Jul 25 12:53:02 debian systemd[1052]: flatpak-portal.service: Consumed 1.156s CPU time.
user@debian:~$ flatpak run --env=G_MESSAGES_DEBUG=cobalt com.brave.Browser//test 
(cobalt:2): cobalt-DEBUG: 12:53:08.874: Loading config file '/app/etc/cobalt.ini'
(cobalt:2): cobalt-DEBUG: 12:53:08.875: Inferred entry point '/app/brave/brave'
(cobalt:2): cobalt-DEBUG: 12:53:08.885: Exec= line is: brave %U
(cobalt:2): cobalt-DEBUG: 12:53:08.885: Zypak is available
(cobalt:2): cobalt-DEBUG: 12:53:08.885: Inferred ExposePids as 'recommended' because Zypak is being used
(cobalt:2): cobalt-DEBUG: 12:53:08.885: Flextop is available
(cobalt:2): cobalt-DEBUG: 12:53:08.885: Inferred sandbox filename 'chrome-sandbox'
Failed to get expose-pids state: Failed to read 'version'
```

With flatpak-portal started:
```
user@debian:~$ systemctl --user start flatpak-portal.service 
user@debian:~$ flatpak run --env=G_MESSAGES_DEBUG=cobalt com.brave.Browser//test 
(cobalt:2): cobalt-DEBUG: 12:54:39.918: Loading config file '/app/etc/cobalt.ini'
(cobalt:2): cobalt-DEBUG: 12:54:39.918: Inferred entry point '/app/brave/brave'
(cobalt:2): cobalt-DEBUG: 12:54:39.929: Exec= line is: brave %U
(cobalt:2): cobalt-DEBUG: 12:54:39.929: Zypak is available
(cobalt:2): cobalt-DEBUG: 12:54:39.929: Inferred ExposePids as 'recommended' because Zypak is being used
(cobalt:2): cobalt-DEBUG: 12:54:39.929: Flextop is available
(cobalt:2): cobalt-DEBUG: 12:54:39.929: Inferred sandbox filename 'chrome-sandbox'
(cobalt:2): cobalt-DEBUG: 12:54:39.934: expose-pids is available
(cobalt:2): cobalt-DEBUG: 12:54:39.947: Flags file '/home/user/.var/app/com.brave.Browser/config/brave-flags.conf' not found
(cobalt:2): cobalt-DEBUG: 12:54:39.947: setenv: TMPDIR=/run/user/1000/app/com.brave.Browser
(cobalt:2): cobalt-DEBUG: 12:54:39.947: setenv: CHROME_WRAPPER=brave
(cobalt:2): cobalt-DEBUG: 12:54:39.947: setenv: ZYPAK_SANDBOX_FILENAME=chrome-sandbox
(cobalt:2): cobalt-DEBUG: 12:54:39.947: setenv: ZYPAK_EXPOSE_WIDEVINE_PATH=/home/user/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/WidevineCdm
(cobalt:2): cobalt-DEBUG: 12:54:39.947: Arg: 'zypak-wrapper.sh'
(cobalt:2): cobalt-DEBUG: 12:54:39.947: Arg: '/app/brave/brave'
(cobalt:2): cobalt-DEBUG: 12:54:39.947: Arg: '--disable-features=WebAssemblyTrapHandler'
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/brave/brave --type=zygote --enable-crashpad --crashpad-handler-pid=14 --enable-crash-reporter=,unknown
[47:47:0725/125440.557823:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by rany2** [comment]
I merged this with ExposePids check disabled. Make another PR removing that line if the bug regarding flatpak-portal is fixed

**Comment by rany2** [comment]
@refi64 I set ExposePids to default again by not specifying it. I didn't test it but I think your latest release fixed it.

**Comment by refi64** [comment]
@rany2 great to hear it's working now! Also THANK YOU for that debugging info, it reduced the time I needed to fix the issue *significantly*.

**Pull request merged**
