### PR TITLE
Enabling support for touchpad gestures navigation

### PR DESCRIPTION
**Pull request by Malom-ctrl**
This let us use gestures to go back/forward when using a laptop touchpad.

Let me know if there is a better way to enable it at some other place

### CODE REVIEW

**Comment by rany2** [comment]
I mean, I'm not really keen about enabling features that could disabled out of the box.  Brave is already buggy and unusable as it stands by default.

**Comment by Malom-ctrl** [comment]
> I mean, I'm not really keen about enabling features that are disabled out of the box. Brave is already buggy and unusable as it stands by default.

It would be nice to have an experimental branch where we can put those features for those who don't mind. Like Wayland, navigation gestures, and more. I think many people would prefer to lose a little bit a little bit of stability for better security and more features.

**Comment by Malom-ctrl** [comment]
Also, unlike wayland, this gesture option cannot be enabled using flags (there is a flag for it but it doesn't work), so it's not as easy to enable after the fact as wayland is.

**Comment by rany2** [comment]
@Malom-ctrl You could just configure your `~/.var/app/com.brave.Browser/config/brave-flags.conf` to enable said features.  It's not like it's being compiled without these features, they're just off by default for you to turn on at your discretion
.

**Comment by Malom-ctrl** [comment]
> @Malom-ctrl You could just configure your `~/.var/app/com.brave.Browser/config/brave-flags.conf` to enable said features. It's not like it's being compiled without these features, they're just off by default for you to turn on at your discretion .

I think we commented at the same time, so you may have missed my second comment stating that the flag doesn't work for some reasons

**Comment by rany2** [comment]
Setting it in brave-flags.conf would have the same exact impact as adding `--enable-features=TouchpadOverscrollHistoryNavigation` to the .desktop file. However if you were referring to `chrome://flags` then I'm willing to consider that it's a possibility that it doesn't quite behave as expected. (brave-flags.conf is read before Brave even starts by Cobalt which then starts Brave up)

Try this:

```
# flatpak kill com.brave.Browser
# edit ~/.var/app/com.brave.Browser/config/brave-flags.conf to include:
features+=TouchpadOverscrollHistoryNavigation
```

**Comment by rany2** [comment]
> I know a simple workaround is to just modify the .desktop i just don't think it's as user friendly as opening the flags page in brave to enable wayland

I understand editing brave-flags.conf is not an intuitive as using chrome://flags but I don't want to be inundated by issues from users because this flatpak enabled experimental features that are off by default for good reason. If the Chromium devs decided this feature isn't ready for primetime, they probably have very good reasons for that.

**Comment by Malom-ctrl** [comment]
I just tried modifying the file itself and it's working, so there is a bug with the chrome://flags flag somehow

**Pull request closed without merging**
