### PR TITLE
Added new images taken on Linux

### PR DESCRIPTION
**Pull request by Angxddeep**
This PR is just adding the images in a new directory. I will do another PR after this one is merged. That PR will change the .xml file, because first I need these images to be in the Repo, only then the build will succeed in the next PR.

### CODE REVIEW

**Comment by rany2** [comment]
Take a look at https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#screenshots for the guidelines. `media/welcome.png` definitely doesn't meet the criteria because there is a checkered background.

Also, it's required to take the screenshot under the latest GNOME.

**Comment by Angxddeep** [comment]
> Take a look at https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#screenshots for the guidelines. `media/welcome.png` definitely doesn't meet the criteria because there is a checkered background.

It's not chequered background, it's just how GitHub shows the image if you download the image it will be clear, and it will look right on the flathub's website

> Also, it's required to take the screenshot under the latest GNOME.

There are no guidelines about taking screenshots only on gnome, it's just that it should be taken on Linux, as a lot of people take screenshots on Windows. Screenshots can be taken on Gnome or KDE Plasma using the default window decorations.

**Comment by rany2** [comment]
> It's not chequered background, it's just how GitHub shows the image if you download the image it will be clear, and it will look right on the flathub's website

I know that. I meant that this transparent background shouldn't be there. Check the guidelines, there's a requirement that you should show the window shadow for both screenshots and that's currently not done.

Also while it doesn't mention that you should use GNOME, I think featured apps need to use a recent GNOME for screenshots. It's the only DE that could satisfy the guideline requirements AFAIK.

**Comment by Angxddeep** [comment]
> I know that. I meant that this transparent background shouldn't be there. Check the guidelines, there's a requirement that you should show the window shadow for both screenshots and that's currently not done.

So what we need to do is make sure that it has rounded corners, as now I have updated the new-tab.png as earlier it was maximized. Now it will show rounded corners, and as for the shadow it will appear on the flathub's website just See this PR that I did  flathub/org.localsend.localsend_app/pull/62 and then the screenshots on the main [site](https://flathub.org/apps/org.localsend.localsend_app) 

> Also while it doesn't mention that you should use GNOME, I think featured apps need to use a recent GNOME for screenshots. It's the only DE that could satisfy the guideline requirements AFAIK.

I just confirmed it with the flatpak team there is no such requirement, both KDE and Gnome can be used with the default window decoration. Also, I think it won't even matter as Brave Decorations will look same for both Gnome and KDE😉

**Comment by Angxddeep** [comment]
@rany2 will you be accepting this?🤔

**Comment by rany2** [comment]
Actually, one last thing. The first screenshot should use the default GTK theme (i.e., no dark theme).

**Comment by Angxddeep** [comment]
> The first screenshot should use the default GTK theme (i.e., no dark theme). 

So, I used the GTK option and only then the shadow appears, so the screenshots are now with shadows because apparently you don't get shadows when using the classic theme? I don't know why is that. Another thing is that the qt option isn't working, it doesn't switch to qt theme when I click on it, btw this only happens on this flatpak version. I remember in the rpm version it used to work just fine. Do you know something about this, and should I create a new issue on main repo?

**Comment by Angxddeep** [comment]
Maybe this qt thing was causing this issue too brave/brave-browser/issues/41439

**Comment by rany2** [comment]
Thanks @Angxddeep, when this is merged you are free to make a new PR that deletes the old screenshots and points to the new locations in the metainfo file.

**Pull request merged**
