### PR TITLE
Use freedesktop 24.08 SDK & runtime

### PR DESCRIPTION
**Pull request by Angxddeep**
As the new stable version of Freedesktop SDK is released. This PR updates the SDK and runtime to freedesktop 24.08.

### CODE REVIEW

**Comment by rany2** [comment]
I'm not comfortable merging this now. Last runtime upgrade broke some random things and I rather wait a bit so we can see what breaks for other apps and handle that.

**Comment by Angxddeep** [comment]
Yeah, I also thought that with something as big as a browser it could have some issues.😅

**Comment by rany2** [comment]
So I guess I'll close this for now.

**Comment by rany2** [comment]
I have switched to 24.08 for Ungoogled Chromium: https://github.com/flathub/io.github.ungoogled_software.ungoogled_chromium/pull/57

Hopefully this catches any issues with 24.08 and Chromium before we migrate it in Brave, but so far it seems to be working OK for my usage. I'll give it a month in case there is any edge cases.

**Pull request closed without merging**
