### PR TITLE
Update runtime to FreeDesktop Platform 21.08

### PR DESCRIPTION
**Pull request by alosarjos**

### CODE REVIEW

**Comment by refi64** [comment]
Zypak's build system still assumes Clang is present (it's not in 21.08), and I haven't gotten around to changing it yet, hang tight!

**Comment by TheEvilSkeleton** [comment]
@alosarjos can you merge with upstream and check if it works now?

**Comment by TheEvilSkeleton** [comment]
Looks like Brave isn't the only one having this problem. Edge is too: https://github.com/flathub/com.microsoft.Edge/pull/70

**Comment by refi64** [comment]
In Chrome I had to [add a patch to get GTK3 to build](https://github.com/flathub/com.google.Chrome/pull/79), that + the updated Zypak version should work.

**Comment by alosarjos** [comment]
> In Chrome I had to [add a patch to get GTK3 to build](https://github.com/flathub/com.google.Chrome/pull/79), that + the updated Zypak version should work.

Why the pipewire removal?

**Comment by TheEvilSkeleton** [comment]
> > In Chrome I had to [add a patch to get GTK3 to build](https://github.com/flathub/com.google.Chrome/pull/79), that + the updated Zypak version should work.
> 
> Why the pipewire removal?

I'm guessing it's because it doesn't need specific versions of PipeWire anymore, so using pipewire >0.2.7 should work.

**Comment by refi64** [comment]
Looks like a Flathub issue this time around.

> Why the pipewire removal?

Whoops I forgot to put it in the commit message, basically Chrome compiles against pipewire 0.3 nowadays.

**Comment by refi64** [comment]
bot, build com.brave.Browser

**Comment by rany2** [comment]
Thanks

**Pull request merged**
